[TBB-194]: Move Flexi-nights calculation to lib-global
lux-group/lib-global pull request #17
Opened 2021-06-10 01:16 UTC by moixons

[[TBB-194]](https://aussiecommerce.atlassian.net/browse/TBB-194?atlOrigin=eyJpIjoiOWRhNzk2N2RhZDY0NDU4NWIxZDdkODUxMTk3ZWNiYzciLCJwIjoiaiJ9): Move Flexi-nights calculation to lib-global

Currently Flexi-nights logic is in svc-public-offers. The goal of this task is to move that logic to a new library to be able to use that logic in other services.

The logic is in https://github.com/lux-group/svc-public-offer/blob/master/src/cache/context/offers/stitchPackageRates.js. That logic gets the package-options and add rates for flexible nights in the package.

2021-06-10 03:52 UTC, keithbro requested changes
This looks good but I am a bit confused about the naming of things. Can we make it consistent and I'll review again?

2021-06-10 03:52 UTC, keithbro commented on src/offer/flexiNights.js
> +const getPakcageOptions = (offerPackage) => (
s/Pakcage/Package/

2021-06-10 03:52 UTC, keithbro commented on compiled/offer/flexiNights.js
> +    packageOptionsId: getPackageOptionId(packageOption, duration),
should it be `packageOptionId` (singular)

2021-06-10 03:52 UTC, keithbro commented on src/offer/flexiNights.js
> +const generatePackageDurations = (offerPackage, addPrices = undefined) => {
I try to avoid boolean arguments because they are hard to read from the calling side:

```
generatePackageDurations(offerPackage, true) // no idea what true means

// vs

generatePackageDurations(offerPackage, { addPrices: true }) // very clear intention
```

2021-06-10 03:52 UTC, keithbro commented on src/offer/flexiNights.js
> +const generatePackageDurations = (offerPackage, addPrices = undefined) => {
The function is called `generatePackageDurations` but the documentation says that it `Generates a list of package options`... should we be consistent one way or the other?

2021-06-10 03:52 UTC, keithbro commented on src/offer/flexiNights.js
> +const generatePackageDurations = (offerPackage, addPrices = undefined) => {
The function is called `generatePackageDurations` while all the others are `getXyz`.. should we be consistent one way or the other?

2021-06-10 03:52 UTC, keithbro commented on test/offer/flexiNights.test.js
> +    it('should return five extra package options', async() => {
there are 6 package options here not 5 🤔

2021-06-10 03:52 UTC, keithbro commented on test/offer/flexiNights.test.js
> +    it('should return rates for the extra package options', async() => {
prices are returned here, not rates

2021-06-10 03:52 UTC, keithbro commented on test/offer/flexiNights.test.js
> +          nightly_price: 0,
should the nightly_price be 0?

2021-06-10 03:52 UTC, keithbro commented on src/offer/flexiNights.js
> +  return (packagePrices) ? {...result, prices: calculatePackageRates(packagePrices, duration)} : result
`prices: calculatePackageRates`

should it be prices or rates? these mean different things

2021-06-10 05:22 UTC, zediah commented on src/offer/flexiNights.js
> +const getPackageOptionId = (packageOption, duration) => {
I don't think we should support ID's like this - this is a concept that belongs to public offer only and it's incorrect anyway!

Not only that, but public offer is adding not the **duration** but the **number of extra days**

e.g. if the base duration is 4 days and we're doing the first flexibile night, it won't be `<id>++5` it'll be `<id>++1`.

Easiest solution is provide the raw data (the number of extra nights added and duration) and let the user of this determine if they want to generate a key from it.

2021-06-10 05:29 UTC, moixons commented on src/offer/flexiNights.js
> +const getPakcageOptions = (offerPackage) => (
Ups

2021-06-10 05:32 UTC, moixons commented on src/offer/flexiNights.js
> +const generatePackageDurations = (offerPackage, addPrices = undefined) => {
I didn't know what was the best name to use, that's why there is this mess up. I'll change it

2021-06-10 05:33 UTC, moixons commented on test/offer/flexiNights.test.js
> +    it('should return five extra package options', async() => {
there is 5 extra plus the one that it was originally. but the library has to create 5 more

2021-06-10 06:05 UTC, moixons commented on test/offer/flexiNights.test.js
> +    it('should return rates for the extra package options', async() => {
Yes, I can see that I need to work on the names again

2021-06-10 06:09 UTC, moixons commented on test/offer/flexiNights.test.js
> +          nightly_price: 0,
Yes, this is what svc-public-offer is doing, so, I just followed what public offer was doing. I don't know if it needs to be different

2021-06-10 06:09 UTC, moixons commented on src/offer/flexiNights.js
> +  return (packagePrices) ? {...result, prices: calculatePackageRates(packagePrices, duration)} : result
Really is rates, but it goes to prices. I'll change that it aligns with the concepts. But almost the mess comes from public-offer

2021-06-10 06:10 UTC, moixons commented on src/offer/flexiNights.js
> +const getPackageOptionId = (packageOption, duration) => {
Yes, good point, I'll change in that way

2021-06-14 23:08 UTC, keithbro approved these changes
This is making good sense to me now, thanks for fixing up the naming.

Couple of questions that are non-blocking 👍  nice work

2021-06-14 23:08 UTC, keithbro commented on src/offer/flexiNights.js
> + * @returns JSON format of a package option
It's not JSON format, its just an object. I think the description of this function is simply `Generates a package option`

2021-06-14 23:08 UTC, keithbro commented on compiled/offer/flexiNights.js
> +  generateAllPackageOptionsWithPrices: generateAllPackageOptionsWithPrices
I'm wondering if we really need two functions - generateAllPackageOptions and generateAllPackageOptionsWithPrices... or if we could just have one that adds the prices, and if a caller didn't want the prices, they could just ignore them?

2021-06-14 23:08 UTC, keithbro commented on test/offer/flexiNights.test.js
> +          nightly_price: 0,
I'd be keen to put the correct value here and have public offer ignore it if it doesn't want to use it.

2021-06-14 23:24 UTC, moixons commented on compiled/offer/flexiNights.js
> +  generateAllPackageOptionsWithPrices: generateAllPackageOptionsWithPrices
Yes, it is possible to do it, but I did like this to reduce the size of the response.

2021-06-14 23:50 UTC, merged